### ISSUE TITLE
About pseudo mask generation

### ISSUE THREAD

**Issue by hxiaoj** [RozDavid/UnScene3D#2]
Hello!
When I run '. scripts/unscene3d_dino_2d3d.sh', I get a new error:

hydra.errors.MissingConfigException: Could not load override hydra/launcher/submitit_slurm

Can you help me?

**Comment by RozDavid** [comment]
hey @hxiaoj,

you are probably missing the hydra launcher plugin. Please refer [here](https://hydra.cc/docs/plugins/submitit_launcher/) for the install command.

**Comment by hxiaoj** [comment]
I find the 192 line in UnScene3D/pseudo_masks/datasets/dataset.py :   filepath = self.data_root / self.data_paths[index] if data_root is None else Path(data_root) / f'{self.data_paths[index]}.pth' 

but I don't know how to get the '.pth' file

**Comment by RozDavid** [comment]
You are right, I missed that part of the preprocessing from this repo, but you can refer directly to [this script](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/downstream/insseg/datasets/scannet.py) to preprocessing the raw scannet data for obtaining the .pth file, which could be used directly as the input there. 

let me know if you need any more help, and in the mantime I will add this part of the preprocessing to the description too.
