### ISSUE TITLE
Can you tell me which file evaluates the AP metrics for class-agnostic instance segmentation results?

### ISSUE THREAD

**Issue by LinLin1031** [RozDavid/UnScene3D#5]
@RozDavid

**Comment by RozDavid** [comment]
You can refer to the file from the line of the class-agnostic instance segmentation metrics found [here](https://github.com/RozDavid/UnScene3D/blob/235186f3808b4f24b030b47d5ea775a9042df908/benchmark/evaluate_semantic_instance.py#L535).
