### ISSUE TITLE
scannet_200_insseg

### ISSUE THREAD

**Issue by Charlie839242** [RozDavid/UnScene3D#7]
Hi, thanks for your great work! when running unscene3d_dino_2d3d.sh, it reports "No such file or directory: 'data/ScanNet/scannet_200_insseg/val.txt'". How can I get scannet_200_insseg?

**Comment by kohjakob** [comment]
I am facing the same issue.

**Comment by RozDavid** [comment]
Hey guys, 

Really fair point, I forgot this bit from the README, but generally we followed the logic of all scannet instance segmentation preprocessing methods. You can find the original script [here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/lib/datasets/preprocessing/scannet200_insseg.py), but if you pull this repo again, I updated the README and the necessary preprocessing scripts in this repo as well. 

Please let me know if you still miss something and thanks for flagging it. 

Cheers, 
David

**Comment by zyjhxd** [comment]
> 嗨，感谢您的出色工作！运行 unscene3d_dino_2d3d.sh 时，系统报告“没有这样的文件或目录：'data/ScanNet/scannet_200_insseg/val.txt'”。我如何获取 scannet_200_insseg？

请问您解决了吗

**Comment by zyjhxd** [comment]
> 我遇到了同样的问题。

请问您解决了嘛

**Comment by RozDavid** [comment]
Please check my previous answer and preprocess the instance segmentation dataset according to [this guideline](https://github.com/RozDavid/UnScene3D?tab=readme-ov-file#data-download-and-preprocessing). 
Closing the issue as solved with updated scripts.

**Comment by zyjhxd** [comment]
> 我遇到了同样的问题。
你好请问解决了吗

**Comment by RozDavid** [comment]
Dear @zyjhxd, 

As I mentioned please refer to [this link](https://github.com/RozDavid/UnScene3D?tab=readme-ov-file#data-download-and-preprocessing) for preprocessing. Yes, it has been solved. 
Also, please use english here as many users, including myself, can't read and speak Chinese and using a translator might lead to misunderstandings. 

Cheers, 
David

**Comment by zyjhxd** [comment]
Okay, thank you for your prompt response. But whether I use the previous script or the updated script to run the second instruction The same error occurs in scripts/unscene3d-dino-2d3d.sh as shown in Figure 1 (I have produced the processed file as shown in Figure 2 using the Python scannet200_insseg.py command). Is there any solution?
![微信截图_20240920170515](https://github.com/user-attachments/assets/096a6a75-3d6c-41d8-83e3-43fdd43aa7bf)
![Uploading 微信截图_20240920170300.png…]()

**Comment by RozDavid** [comment]
I think the only thing is missing your train/val/test splits text file. Can you check in the parent folder of your screenshot?

**Comment by zyjhxd** [comment]
But at the end of my file, there are three files that separate the datasets
![Uploading 微信截图_20240920173712.png…]()

**Comment by RozDavid** [comment]
hmm, I can't seem to see this image (also previous comment figure 2 is still in updating stage)

**Comment by zyjhxd** [comment]
The parent folder is shown in the picture, with only one folder.
![微信截图_20240920174015](https://github.com/user-attachments/assets/93d43d44-0a07-482c-81fc-d0d209773f72)
The image of the previous comment is as follows
![微信截图_20240920173712](https://github.com/user-attachments/assets/513b3f85-2654-4583-bcc9-d1c19c02fd13)

**Comment by RozDavid** [comment]
right, this looks correct. so if you run the original script, the file (val.txt) should be found as the paths are correct (assuming the here shown data folder lives in the root repo path which is not shown on this screenshot).

**Comment by zyjhxd** [comment]
But I run the script When generating pseudo labels with scripts/unscene3d.dino-2d3d.sh, there is an error message stating that the file train.exe cannot be found. However, this file does exist in this path, as shown in the figure. What is the reason for this?
![2](https://github.com/user-attachments/assets/43f6ab0c-5362-4c5f-9858-3cec124cbf2e)
![3](https://github.com/user-attachments/assets/fc566d9c-66e2-4982-9aa8-69d28a218609)
![4](https://github.com/user-attachments/assets/2837bd6c-da51-41a2-81ba-c7e0c0b5ebcf)
![5](https://github.com/user-attachments/assets/125946c3-48a9-4194-a3b5-596a6feaa272)
